import type { LocalizedText, Question } from '../../../core/types'
import { DIFFICULTY } from './meta'

const t = (de: string, en: string): LocalizedText => ({ de, en })
const opt = (id: string, de: string, en: string) => ({ id, label: t(de, en) })
const base = { difficulty: DIFFICULTY } as const

/**
 * Fragenpool Rechnungen, Grundlagen: 15 Single, 5 Multi, 3 Slider, 2 Zuordnung.
 * Quellsprache Deutsch. Alle Fragen stehen unter fachlichem [REVIEW] durch Sascha.
 * Multiple Select hat durchgehend genau 3 richtige aus 5 Optionen.
 */
export const QUESTIONS: readonly Question[] = [
  // ---------- Single Choice (15) ----------
  {
    ...base,
    id: 'rg-b-001',
    type: 'single',
    prompt: t('Was ist eine Rechnung im Kern?', 'What is an invoice at its core?'),
    options: [
      opt('a', 'Die Abrechnung einer Lieferung oder Leistung mit Zahlungsaufforderung', 'The billing of a delivery or service, requesting payment'),
      opt('b', 'Eine unverbindliche Preisauskunft', 'A non-binding price quote'),
      opt('c', 'Eine Bestätigung des Wareneingangs', 'A confirmation of goods receipt'),
      opt('d', 'Ein interner Freigabevermerk', 'An internal approval note'),
    ],
    correctOptionId: 'a',
    explanation: t(
      'Die Rechnung hält fest, wer was für wen erbracht hat und welcher Betrag zu zahlen ist.',
      'The invoice records who provided what to whom and how much is owed.',
    ),
  },
  {
    ...base,
    id: 'rg-b-002',
    type: 'single',
    prompt: t('Was ermöglicht eine ordnungsgemäße Rechnung dem Empfänger steuerlich?', 'What does a proper invoice enable for the recipient, tax-wise?'),
    options: [
      opt('a', 'Den Vorsteuerabzug', 'The input tax deduction'),
      opt('b', 'Die Befreiung von der Umsatzsteuer', 'Exemption from VAT'),
      opt('c', 'Einen automatischen Skontoabzug', 'An automatic early-payment discount'),
      opt('d', 'Die Verkürzung der Aufbewahrungsfrist', 'A shorter retention period'),
    ],
    correctOptionId: 'a',
    explanation: t(
      'Nur mit einer ordnungsgemäßen Rechnung kann der Empfänger die ausgewiesene Umsatzsteuer als Vorsteuer geltend machen.',
      'Only a proper invoice lets the recipient claim the stated VAT as input tax.',
    ),
  },
  {
    ...base,
    id: 'rg-b-003',
    type: 'single',
    prompt: t('Welche Angabe gehört zu den Pflichtangaben einer vollen Rechnung?', 'Which item is a mandatory detail on a full invoice?'),
    options: [
      opt('a', 'Eine fortlaufende Rechnungsnummer', 'A sequential invoice number'),
      opt('b', 'Das Firmenlogo', 'The company logo'),
      opt('c', 'Die Bankleitzahl', 'The bank routing number'),
      opt('d', 'Die Anzahl der Mitarbeitenden', 'The number of employees'),
    ],
    correctOptionId: 'a',
    explanation: t(
      'Die fortlaufende Nummer macht Rechnungen eindeutig identifizierbar und lückenlos nachvollziehbar.',
      'The sequential number makes invoices uniquely identifiable and traceable without gaps.',
    ),
  },
  {
    ...base,
    id: 'rg-b-004',
    type: 'single',
    prompt: t('Bis zu welchem Betrag gilt eine Rechnung in Deutschland als Kleinbetragsrechnung?', 'Up to which amount does an invoice count as a small-amount invoice in Germany?'),
    options: [opt('a', '250 Euro', 'EUR 250'), opt('b', '100 Euro', 'EUR 100'), opt('c', '500 Euro', 'EUR 500'), opt('d', '1.000 Euro', 'EUR 1,000')],
    correctOptionId: 'a',
    explanation: t(
      'Bis 250 Euro Bruttobetrag gelten erleichterte Anforderungen an die Rechnung.',
      'Up to a gross amount of EUR 250, simplified requirements apply to the invoice.',
    ),
  },
  {
    ...base,
    id: 'rg-b-005',
    type: 'single',
    prompt: t('Was muss auch eine Kleinbetragsrechnung enthalten?', 'What must even a small-amount invoice contain?'),
    options: [
      opt('a', 'Den Bruttobetrag samt Steuersatz', 'The gross amount including the tax rate'),
      opt('b', 'Eine fortlaufende Rechnungsnummer', 'A sequential invoice number'),
      opt('c', 'Die Anschrift des Empfängers', 'The recipient\'s address'),
      opt('d', 'Den gesondert ausgewiesenen Steuerbetrag', 'The separately stated tax amount'),
    ],
    correctOptionId: 'a',
    explanation: t(
      'Rechnungsnummer, Empfängeranschrift und gesonderter Steuerbetrag dürfen entfallen, der Bruttobetrag mit Steuersatz nicht.',
      'The invoice number, recipient address and separately stated tax amount may be omitted, but not the gross amount with the tax rate.',
    ),
  },
  {
    ...base,
    id: 'rg-b-006',
    type: 'single',
    prompt: t('Was ist ein Angebot im Geschäftsablauf?', 'What is a quote in the business process?'),
    options: [
      opt('a', 'Eine unverbindliche oder befristet bindende Ankündigung vor dem Geschäft', 'A non-binding or time-limited announcement before the deal'),
      opt('b', 'Die Bestätigung der tatsächlichen Lieferung', 'Confirmation of the actual delivery'),
      opt('c', 'Die Zahlungsaufforderung nach Leistungserbringung', 'The payment request after the service is rendered'),
      opt('d', 'Der Buchungsbeleg für die Finanzbuchhaltung', 'The posting document for the general ledger'),
    ],
    correctOptionId: 'a',
    explanation: t(
      'Das Angebot kommt vom Verkäufer vor dem Geschäft und bindet meist nur befristet oder gar nicht.',
      'The quote comes from the seller before the deal and is usually binding only for a limited time, if at all.',
    ),
  },
  {
    ...base,
    id: 'rg-b-007',
    type: 'single',
    prompt: t('Was bestätigt ein Lieferschein?', 'What does a delivery note confirm?'),
    options: [
      opt('a', 'Was tatsächlich geliefert wurde', 'What was actually delivered'),
      opt('b', 'Den vereinbarten Preis', 'The agreed price'),
      opt('c', 'Die Zahlungsfrist', 'The payment term'),
      opt('d', 'Den Vorsteuerabzug', 'The input tax deduction'),
    ],
    correctOptionId: 'a',
    explanation: t('Der Lieferschein begleitet die Ware und bestätigt die tatsächliche Lieferung, meist ohne Preise.', 'The delivery note travels with the goods and confirms the actual delivery, usually without prices.'),
  },
  {
    ...base,
    id: 'rg-b-008',
    type: 'single',
    prompt: t('Welches Dokument begründet die Zahlungspflicht?', 'Which document creates the payment obligation?'),
    options: [opt('a', 'Die Rechnung', 'The invoice'), opt('b', 'Das Angebot', 'The quote'), opt('c', 'Der Lieferschein', 'The delivery note'), opt('d', 'Die Bestellung', 'The order')],
    correctOptionId: 'a',
    explanation: t('Nur die Rechnung fordert die Zahlung für die tatsächlich erbrachte Leistung und begründet den Vorsteuerabzug.', 'Only the invoice demands payment for the service actually rendered and creates the input tax deduction.'),
  },
  {
    ...base,
    id: 'rg-b-009',
    type: 'single',
    prompt: t('Wie heißt der gesamte Weg von der Bedarfserkennung bis zur Bezahlung?', 'What is the whole path from identifying a need to payment called?'),
    options: [opt('a', 'Purchase-to-Pay', 'Purchase-to-pay'), opt('b', 'Order-to-Cash', 'Order-to-cash'), opt('c', 'Record-to-Report', 'Record-to-report'), opt('d', 'Plan-to-Produce', 'Plan-to-produce')],
    correctOptionId: 'a',
    explanation: t('Purchase-to-Pay beschreibt den Weg auf der Einkaufsseite: Bedarf, Bestellung, Wareneingang, Rechnung, Zahlung.', 'Purchase-to-pay describes the path on the buying side: need, order, goods receipt, invoice, payment.'),
  },
  {
    ...base,
    id: 'rg-b-010',
    type: 'single',
    prompt: t('Wie heißt der Abgleich von Bestellung, Wareneingang und Rechnung?', 'What is the comparison of order, goods receipt and invoice called?'),
    options: [opt('a', 'Drei-Wege-Abgleich', 'Three-way matching'), opt('b', 'Zwei-Faktor-Prüfung', 'Two-factor check'), opt('c', 'Vier-Corner-Modell', 'Four-corner model'), opt('d', 'Skontoprüfung', 'Discount check')],
    correctOptionId: 'a',
    explanation: t('Erst wenn Bestellung, Lieferung und Rechnung zusammenpassen, wird bezahlt.', 'Payment happens only once order, delivery and invoice match up.'),
  },
  {
    ...base,
    id: 'rg-b-011',
    type: 'single',
    prompt: t('Was ist der erste Schritt, wenn eine Rechnung im Unternehmen ankommt?', 'What is the first step once an invoice arrives at a company?'),
    options: [opt('a', 'Der Eingang, also wo und wie sie ankommt', 'Intake: where and how it arrives'), opt('b', 'Die Zahlung', 'The payment'), opt('c', 'Die Buchung', 'The posting'), opt('d', 'Die Archivierung', 'The archiving')],
    correctOptionId: 'a',
    explanation: t('Der Rechnungseingang läuft in fünf Schritten: Eingang, Prüfung, Freigabe, Buchung, Zahlung.', 'Invoice receipt runs in five steps: intake, matching, approval, posting, payment.'),
  },
  {
    ...base,
    id: 'rg-b-012',
    type: 'single',
    prompt: t('Warum zählt Geschwindigkeit bei der Rechnungsverarbeitung?', 'Why does speed matter in invoice processing?'),
    options: [
      opt('a', 'Zahlungsfristen und Skonto-Fenster laufen ab dem Rechnungsdatum', 'Payment terms and discount windows run from the invoice date'),
      opt('b', 'Rechnungen verfallen nach 48 Stunden', 'Invoices expire after 48 hours'),
      opt('c', 'Nur schnelle Rechnungen sind steuerlich gültig', 'Only quickly processed invoices are tax-valid'),
      opt('d', 'Langsame Bearbeitung senkt automatisch die Steuer', 'Slow processing automatically lowers the tax'),
    ],
    correctOptionId: 'a',
    explanation: t('Wer zu spät prüft, verpasst den Skonto oder zahlt Verzugszinsen.', 'Checking too late means missing the discount or paying late fees.'),
  },
  {
    ...base,
    id: 'rg-b-013',
    type: 'single',
    prompt: t('Wie lange müssen Rechnungen in Deutschland in der Regel aufbewahrt werden?', 'How long must invoices in Germany generally be retained?'),
    options: [opt('a', '10 Jahre', '10 years'), opt('b', '2 Jahre', '2 years'), opt('c', '5 Jahre', '5 years'), opt('d', '20 Jahre', '20 years')],
    correctOptionId: 'a',
    explanation: t('Die gesetzliche Aufbewahrungspflicht für Rechnungen beträgt in der Regel zehn Jahre.', 'The statutory retention period for invoices is generally ten years.'),
  },
  {
    ...base,
    id: 'rg-b-014',
    type: 'single',
    prompt: t('Was bedeutet Kontieren?', 'What does coding an invoice mean?'),
    options: [
      opt('a', 'Eine Rechnung Sachkonto, Kostenstelle und Steuerschlüssel zuordnen', 'Assigning an invoice to a general ledger account, cost centre and tax code'),
      opt('b', 'Eine Rechnung ins Archiv verschieben', 'Moving an invoice to the archive'),
      opt('c', 'Eine Rechnung an den Empfänger zurücksenden', 'Sending an invoice back to the recipient'),
      opt('d', 'Eine Rechnung digital signieren', 'Digitally signing an invoice'),
    ],
    correctOptionId: 'a',
    explanation: t('Kontieren heißt, die Rechnung den richtigen Konten fuer Buchhaltung und Steuer zuzuordnen.', 'Coding means assigning the invoice to the right accounts for bookkeeping and tax.'),
  },
  {
    ...base,
    id: 'rg-b-015',
    type: 'single',
    prompt: t('Was prüft die rechnerische Prüfung einer Rechnung?', 'What does the arithmetic check of an invoice verify?'),
    options: [
      opt('a', 'Ob Mengen, Preise und Steuer korrekt berechnet sind', 'Whether quantities, prices and tax are calculated correctly'),
      opt('b', 'Ob die Leistung überhaupt erbracht wurde', 'Whether the service was provided at all'),
      opt('c', 'Ob der Empfänger existiert', 'Whether the recipient exists'),
      opt('d', 'Ob die Rechnung archiviert wurde', 'Whether the invoice has been archived'),
    ],
    correctOptionId: 'a',
    explanation: t('Die sachliche Prüfung fragt, ob die Leistung erbracht wurde, die rechnerische, ob die Zahlen stimmen.', 'The factual check asks whether the service was provided, the arithmetic check whether the numbers add up.'),
  },

  // ---------- Multiple Select (5) ----------
  {
    ...base,
    id: 'rg-b-016',
    type: 'multi',
    prompt: t('Welche Angaben gehören zu den Pflichtangaben einer vollen Rechnung?', 'Which items are mandatory details on a full invoice?'),
    options: [
      opt('a', 'Fortlaufende Rechnungsnummer', 'Sequential invoice number'),
      opt('b', 'Steuernummer oder USt-IdNr.', 'Tax number or VAT ID'),
      opt('c', 'Zeitpunkt der Lieferung oder Leistung', 'Date of delivery or service'),
      opt('d', 'Bankleitzahl des Empfängers', 'Recipient\'s bank routing number'),
      opt('e', 'Firmenlogo', 'Company logo'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Bankleitzahl und Logo sind keine Pflichtangaben nach Umsatzsteuerrecht.', 'The bank routing number and logo are not mandatory details under VAT law.'),
  },
  {
    ...base,
    id: 'rg-b-017',
    type: 'multi',
    prompt: t('Welche Aussagen zum Unterschied zwischen Angebot, Auftragsbestätigung und Rechnung sind richtig?', 'Which statements about the difference between quote, order confirmation and invoice are correct?'),
    options: [
      opt('a', 'Das Angebot kommt vor dem Geschäft', 'The quote comes before the deal'),
      opt('b', 'Die Auftragsbestätigung folgt nach der Bestellung', 'The order confirmation follows the order'),
      opt('c', 'Nur die Rechnung begründet die Zahlungspflicht', 'Only the invoice creates the payment obligation'),
      opt('d', 'Ein Angebot ist immer rechtlich bindend', 'A quote is always legally binding'),
      opt('e', 'Ein Lieferschein enthält immer den vollen Preis', 'A delivery note always contains the full price'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Angebote binden oft nur befristet oder gar nicht, und Lieferscheine enthalten meist keine Preise.', 'Quotes are often binding only for a limited time or not at all, and delivery notes usually contain no prices.'),
  },
  {
    ...base,
    id: 'rg-b-018',
    type: 'multi',
    prompt: t('Welche Schritte gehören zu einem geordneten Rechnungseingang?', 'Which steps belong to an orderly invoice intake process?'),
    options: [
      opt('a', 'Prüfung gegen Bestellung und Wareneingang', 'Matching against order and goods receipt'),
      opt('b', 'Freigabe durch die zuständige Stelle', 'Approval by the responsible party'),
      opt('c', 'Buchung in die Finanzbuchhaltung', 'Posting to the general ledger'),
      opt('d', 'Sofortige Zahlung ohne Prüfung', 'Immediate payment without checking'),
      opt('e', 'Vernichtung der Rechnung nach dem Lesen', 'Destroying the invoice after reading it'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Ungeprüft zahlen und Belege vernichten widerspricht Prüfpflicht und Aufbewahrungspflicht.', 'Paying unchecked and destroying documents contradicts the duty to verify and the retention duty.'),
  },
  {
    ...base,
    id: 'rg-b-019',
    type: 'multi',
    prompt: t('Welche Aussagen zur Kontierung sind richtig?', 'Which statements about coding invoices are correct?'),
    options: [
      opt('a', 'Ein Sachkonto ordnet die Art der Ausgabe zu', 'A general ledger account assigns the type of expense'),
      opt('b', 'Eine Kostenstelle ordnet den verursachenden Bereich zu', 'A cost centre assigns the responsible area'),
      opt('c', 'Ein Steuerschlüssel regelt die Umsatzsteuerbehandlung', 'A tax code governs the VAT treatment'),
      opt('d', 'Kontierung ersetzt die sachliche und rechnerische Prüfung', 'Coding replaces the factual and arithmetic check'),
      opt('e', 'Kontierung ist erst ab 1.000 Euro nötig', 'Coding is only needed above EUR 1,000'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Kontierung folgt der Prüfung, sie ersetzt sie nicht, und sie gilt unabhängig vom Betrag.', 'Coding follows the check, it does not replace it, and it applies regardless of the amount.'),
  },
  {
    ...base,
    id: 'rg-b-020',
    type: 'multi',
    prompt: t('Welche Aussagen zu Übertragungswegen vor der E-Rechnung sind richtig?', 'Which statements about transmission paths before e-invoicing are correct?'),
    options: [
      opt('a', 'EDI ist ein strukturierter Datenaustausch nach festen Regeln', 'EDI is a structured data exchange under fixed rules'),
      opt('b', 'Papier und Fax kamen ohne strukturierte Daten aus', 'Paper and fax worked without structured data'),
      opt('c', 'Bei PDF per E-Mail musste jemand die Daten am Ende trotzdem eintippen', 'With PDF by email, someone still had to re-type the data at the end'),
      opt('d', 'Blockchain war der Standardweg vor der E-Rechnungspflicht', 'Blockchain was the standard path before the e-invoicing mandate'),
      opt('e', 'EDI erfüllt automatisch die gesetzliche Definition der E-Rechnung', 'EDI automatically meets the legal definition of an e-invoice'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Blockchain spielte praktisch keine Rolle, und EDI erfüllt die enge gesetzliche E-Rechnungsdefinition nicht automatisch.', 'Blockchain played virtually no role, and EDI does not automatically meet the narrow legal e-invoice definition.'),
  },

  // ---------- Slider (3) ----------
  {
    ...base,
    id: 'rg-b-021',
    type: 'slider',
    prompt: t('Bis zu welchem Betrag gilt eine Rechnung in Deutschland als Kleinbetragsrechnung?', 'Up to which amount does an invoice count as a small-amount invoice in Germany?'),
    min: 0,
    max: 1_000,
    step: 10,
    unit: t('EUR', 'EUR'),
    target: 250,
    tolerance: 0,
    zeroAt: 200,
    explanation: t('Die Grenze liegt bei 250 Euro Bruttobetrag.', 'The threshold is EUR 250 gross.'),
  },
  {
    ...base,
    id: 'rg-b-022',
    type: 'slider',
    prompt: t('Wie viele Jahre müssen Rechnungen in Deutschland in der Regel aufbewahrt werden?', 'How many years must invoices in Germany generally be retained?'),
    min: 0,
    max: 20,
    step: 1,
    unit: t('Jahre', 'years'),
    target: 10,
    tolerance: 0,
    zeroAt: 5,
    explanation: t('Die gesetzliche Aufbewahrungsfrist beträgt in der Regel zehn Jahre.', 'The statutory retention period is generally ten years.'),
  },
  {
    ...base,
    id: 'rg-b-023',
    type: 'slider',
    prompt: t(
      'In wie vielen Schritten läuft der Rechnungseingang typischerweise ab (Eingang, Prüfung, Freigabe, Buchung, Zahlung)?',
      'In how many steps does invoice receipt typically run (intake, matching, approval, posting, payment)?',
    ),
    min: 0,
    max: 10,
    step: 1,
    unit: t('Schritte', 'steps'),
    target: 5,
    tolerance: 0,
    zeroAt: 3,
    explanation: t('Fuenf Schritte: Eingang, Prüfung, Freigabe, Buchung, Zahlung.', 'Five steps: intake, matching, approval, posting, payment.'),
  },

  // ---------- Zuordnung (2) ----------
  {
    ...base,
    id: 'rg-b-024',
    type: 'matching',
    prompt: t('Ordne jedem Dokument seine Rolle im Geschäftsablauf zu.', 'Match each document to its role in the business process.'),
    left: [
      opt('angebot', 'Angebot', 'Quote'),
      opt('bestellung', 'Bestellung', 'Order'),
      opt('auftrag', 'Auftragsbestätigung', 'Order confirmation'),
      opt('lieferschein', 'Lieferschein', 'Delivery note'),
      opt('rechnung', 'Rechnung', 'Invoice'),
    ],
    right: [
      opt('vor', 'Unverbindliche Ankündigung vor dem Geschäft', 'Non-binding announcement before the deal'),
      opt('ausloesen', 'Löst den Beschaffungsprozess aus', 'Triggers the procurement process'),
      opt('bestaetigt', 'Bestätigt die Bedingungen nach der Bestellung', 'Confirms the terms after the order'),
      opt('liefert', 'Bestätigt die tatsächliche Lieferung, meist ohne Preise', 'Confirms the actual delivery, usually without prices'),
      opt('fordert', 'Fordert die Zahlung und begründet den Vorsteuerabzug', 'Demands payment and creates the input tax deduction'),
    ],
    pairs: { angebot: 'vor', bestellung: 'ausloesen', auftrag: 'bestaetigt', lieferschein: 'liefert', rechnung: 'fordert' },
    explanation: t('Jedes Dokument gehört zu einer eigenen Phase des Geschäftsablaufs.', 'Each document belongs to its own phase of the business process.'),
  },
  {
    ...base,
    id: 'rg-b-025',
    type: 'matching',
    prompt: t('Ordne jeden Begriff seiner Bedeutung zu.', 'Match each term to its meaning.'),
    left: [
      opt('kontierung', 'Kontierung', 'Coding'),
      opt('dreiwege', 'Drei-Wege-Abgleich', 'Three-way matching'),
      opt('skonto', 'Skonto', 'Early-payment discount'),
      opt('vorsteuer', 'Vorsteuerabzug', 'Input tax deduction'),
      opt('aufbewahrung', 'Aufbewahrungspflicht', 'Retention duty'),
    ],
    right: [
      opt('konten', 'Zuordnung zu Sachkonto, Kostenstelle und Steuerschlüssel', 'Assignment to a ledger account, cost centre and tax code'),
      opt('vergleich', 'Vergleich von Bestellung, Wareneingang und Rechnung', 'Comparison of order, goods receipt and invoice'),
      opt('nachlass', 'Preisnachlass bei schneller Zahlung', 'Price reduction for fast payment'),
      opt('gegenrechnen', 'Recht, gezahlte Umsatzsteuer gegenzurechnen', 'Right to offset VAT already paid'),
      opt('jahre', 'Pflicht, Belege über Jahre nachvollziehbar zu halten', 'Duty to keep documents traceable for years'),
    ],
    pairs: { kontierung: 'konten', dreiwege: 'vergleich', skonto: 'nachlass', vorsteuer: 'gegenrechnen', aufbewahrung: 'jahre' },
    explanation: t('Diese fünf Begriffe tauchen in fast jedem Rechnungseingangsprozess auf.', 'These five terms come up in almost every invoice intake process.'),
  },
]
