import type { LocalizedText, Question } from '../../../core/types'
import { DIFFICULTY } from './meta'

const t = (de: string, en: string): LocalizedText => ({ de, en })
const opt = (id: string, de: string, en: string) => ({ id, label: t(de, en) })
const base = { difficulty: DIFFICULTY } as const

/**
 * Fragenpool E-Rechnung, Vertiefung: 15 Single, 5 Multi, 3 Slider, 2 Zuordnung.
 * Quellsprache Deutsch. Alle Fragen stehen unter fachlichem [REVIEW] durch Sascha.
 * Multiple Select hat durchgehend genau 3 richtige aus 5 Optionen.
 */
export const QUESTIONS: readonly Question[] = [
  // ---------- Single Choice (15) ----------
  {
    ...base,
    id: 'ei-a-001',
    type: 'single',
    prompt: t('Was definiert EN 16931 in erster Linie?', 'What does EN 16931 primarily define?'),
    options: [
      opt('a', 'Ein semantisches Datenmodell, kein Dateiformat', 'A semantic data model, not a file format'),
      opt('b', 'Ein konkretes Dateiformat mit fester Endung', 'A specific file format with a fixed extension'),
      opt('c', 'Ein Transportprotokoll', 'A transport protocol'),
      opt('d', 'Eine Verschlüsselungsmethode', 'An encryption method'),
    ],
    correctOptionId: 'a',
    explanation: t('Die Norm legt Bedeutung und Struktur der Informationselemente fest, nicht ihre technische Codierung.', 'The standard defines the meaning and structure of the information elements, not their technical encoding.'),
  },
  {
    ...base,
    id: 'ei-a-002',
    type: 'single',
    prompt: t('Wie sind die Informationselemente von EN 16931 organisiert?', 'How are the information elements of EN 16931 organised?'),
    options: [
      opt('a', 'In Gruppen wie Rechnungssteller, Empfänger und Rechnungszeilen', 'In groups such as seller, buyer and invoice lines'),
      opt('b', 'Alphabetisch nach Feldnamen', 'Alphabetically by field name'),
      opt('c', 'Nach Dateigröße', 'By file size'),
      opt('d', 'Nach Land des Empfängers', 'By the recipient\'s country'),
    ],
    correctOptionId: 'a',
    explanation: t('Jede nationale Ausprägung bildet dieselben Gruppen ab, nur die Syntax unterscheidet sich.', 'Every national specialisation maps the same groups, only the syntax differs.'),
  },
  {
    ...base,
    id: 'ei-a-003',
    type: 'single',
    prompt: t('Was unterscheidet UBL und UN/CEFACT CII vor allem?', 'What mainly distinguishes UBL and UN/CEFACT CII?'),
    options: [
      opt('a', 'Benennung und Verschachtelung der Felder, nicht die Informationselemente selbst', 'Field naming and nesting, not the information elements themselves'),
      opt('b', 'CII ist keine XML-Syntax', 'CII is not an XML syntax'),
      opt('c', 'UBL erlaubt keine Rechnungszeilen', 'UBL does not allow invoice lines'),
      opt('d', 'Nur eine der beiden ist EN-16931-konform', 'Only one of the two is EN 16931 compliant'),
    ],
    correctOptionId: 'a',
    explanation: t('Beide Syntaxen transportieren dieselben Informationselemente, nur strukturell verschieden.', 'Both syntaxes carry the same information elements, just structured differently.'),
  },
  {
    ...base,
    id: 'ei-a-004',
    type: 'single',
    prompt: t('Was ist eine CIUS?', 'What is a CIUS?'),
    options: [
      opt('a', 'Eine nationale oder branchenspezifische Einschränkung der Norm mit Pflichtfeldern', 'A national or sector-specific restriction of the standard with mandatory fields'),
      opt('b', 'Ein Validierungswerkzeug', 'A validation tool'),
      opt('c', 'Ein Transportprotokoll fuer Peppol', 'A transport protocol for Peppol'),
      opt('d', 'Eine Archivierungspflicht', 'An archiving obligation'),
    ],
    correctOptionId: 'a',
    explanation: t('CIUS steht fuer Core Invoice Usage Specification und macht optionale Felder verpflichtend.', 'CIUS stands for Core Invoice Usage Specification and makes optional fields mandatory.'),
  },
  {
    ...base,
    id: 'ei-a-005',
    type: 'single',
    prompt: t('Was ist XRechnung im Sinne der Norm?', 'What is XRechnung in terms of the standard?'),
    options: [
      opt('a', 'Eine CIUS fuer den deutschen öffentlichen Sektor', 'A CIUS for the German public sector'),
      opt('b', 'Eine eigene, von EN 16931 unabhängige Norm', 'A separate standard independent of EN 16931'),
      opt('c', 'Ein Transportnetzwerk', 'A transport network'),
      opt('d', 'Ein PDF-Archivierungsformat', 'A PDF archiving format'),
    ],
    correctOptionId: 'a',
    explanation: t('XRechnung schraenkt die Norm ein und macht bestimmte Felder verpflichtend.', 'XRechnung restricts the standard and makes certain fields mandatory.'),
  },
  {
    ...base,
    id: 'ei-a-006',
    type: 'single',
    prompt: t('Was macht eine Extension?', 'What does an extension do?'),
    options: [
      opt('a', 'Sie ergänzt zusätzliche, branchenspezifische Felder', 'It adds extra, sector-specific fields'),
      opt('b', 'Sie entfernt Pflichtfelder der Norm', 'It removes mandatory fields of the standard'),
      opt('c', 'Sie ersetzt die Syntax UBL durch CII', 'It replaces the UBL syntax with CII'),
      opt('d', 'Sie hebt die Validierungspflicht auf', 'It lifts the validation requirement'),
    ],
    correctOptionId: 'a',
    explanation: t('Extensions bleiben zur Basisnorm kompatibel und ergaenzen sie nur.', 'Extensions stay compatible with the base standard and only add to it.'),
  },
  {
    ...base,
    id: 'ei-a-007',
    type: 'single',
    prompt: t('Welche Validierungsstufe prüft, ob das XML wohlgeformt ist?', 'Which validation stage checks whether the XML is well-formed?'),
    options: [opt('a', 'Schema-Validierung', 'Schema validation'), opt('b', 'Schematron-Regeln', 'Schematron rules'), opt('c', 'Sachliche Prüfung', 'Factual check'), opt('d', 'Kontierung', 'Coding')],
    correctOptionId: 'a',
    explanation: t('Die Schema-Validierung prüft Struktur und Wohlgeformtheit des XML.', 'Schema validation checks the structure and well-formedness of the XML.'),
  },
  {
    ...base,
    id: 'ei-a-008',
    type: 'single',
    prompt: t('Welche Validierungsstufe prüft semantische Geschäftsregeln?', 'Which validation stage checks semantic business rules?'),
    options: [opt('a', 'Schematron-Regeln', 'Schematron rules'), opt('b', 'Schema-Validierung', 'Schema validation'), opt('c', 'Die Leitweg-ID-Pruefung', 'The Leitweg-ID check'), opt('d', 'Die PDF/A-3-Pruefung', 'The PDF/A-3 check')],
    correctOptionId: 'a',
    explanation: t('Schematron prüft Regeln wie korrekt gebildete Summen.', 'Schematron checks rules such as correctly formed totals.'),
  },
  {
    ...base,
    id: 'ei-a-009',
    type: 'single',
    prompt: t('Was bleibt bei unterschiedlichen ZUGFeRD-Profilen gleich?', 'What stays the same across different ZUGFeRD profiles?'),
    options: [
      opt('a', 'Das sichtbare PDF', 'The visible PDF'),
      opt('b', 'Die Menge der eingebetteten Daten', 'The amount of embedded data'),
      opt('c', 'Der Dateiname', 'The file name'),
      opt('d', 'Die Anzahl der Rechnungszeilen', 'The number of invoice lines'),
    ],
    correctOptionId: 'a',
    explanation: t('Nur der Detailgrad der eingebetteten XML ändert sich je Profil, das PDF-Erscheinungsbild bleibt gleich.', 'Only the detail level of the embedded XML changes per profile, the PDF appearance stays the same.'),
  },
  {
    ...base,
    id: 'ei-a-010',
    type: 'single',
    prompt: t('Wofür steht PDF/A-3 im Zusammenhang mit ZUGFeRD?', 'What is PDF/A-3 for in the context of ZUGFeRD?'),
    options: [
      opt('a', 'Ein Langzeitarchivierungsstandard, der eingebettete Dateien erlaubt', 'A long-term archiving standard that allows embedded files'),
      opt('b', 'Ein Verschlüsselungsverfahren', 'An encryption method'),
      opt('c', 'Eine Peppol-Profilstufe', 'A Peppol profile level'),
      opt('d', 'Ein Validierungswerkzeug', 'A validation tool'),
    ],
    correctOptionId: 'a',
    explanation: t('PDF/A-3 macht das PDF selbst archivierbar, obwohl eine XML-Datei eingebettet ist.', 'PDF/A-3 makes the PDF itself archivable even though an XML file is embedded.'),
  },
  {
    ...base,
    id: 'ei-a-011',
    type: 'single',
    prompt: t('Wozu dient die Leitweg-ID?', 'What is the Leitweg-ID for?'),
    options: [
      opt('a', 'Sie identifiziert die zuständige Verwaltungsstelle und leitet die Rechnung intern weiter', 'It identifies the responsible administrative body and routes the invoice internally'),
      opt('b', 'Sie verschlüsselt die Rechnung', 'It encrypts the invoice'),
      opt('c', 'Sie ersetzt die Steuernummer', 'It replaces the tax number'),
      opt('d', 'Sie ist ein Peppol-Profil', 'It is a Peppol profile'),
    ],
    correctOptionId: 'a',
    explanation: t('Ohne passende Leitweg-ID findet die Rechnung intern nicht die richtige Stelle.', 'Without a matching Leitweg-ID, the invoice does not find the right place internally.'),
  },
  {
    ...base,
    id: 'ei-a-012',
    type: 'single',
    prompt: t('Was passiert ohne gültige Leitweg-ID bei Rechnungen an die öffentliche Verwaltung?', 'What happens without a valid Leitweg-ID for invoices to public administration?'),
    options: [
      opt('a', 'Die Rechnung wird von der Empfangsplattform zurückgewiesen', 'The invoice is rejected by the receiving platform'),
      opt('b', 'Die Rechnung wird automatisch bezahlt', 'The invoice is paid automatically'),
      opt('c', 'Die Umsatzsteuer entfällt', 'VAT no longer applies'),
      opt('d', 'Nichts, die ID ist optional', 'Nothing, the ID is optional'),
    ],
    correctOptionId: 'a',
    explanation: t('Eine fehlende oder falsche Leitweg-ID fuehrt zur Zurueckweisung, unabhaengig vom sonstigen Inhalt.', 'A missing or wrong Leitweg-ID leads to rejection, regardless of the rest of the content.'),
  },
  {
    ...base,
    id: 'ei-a-013',
    type: 'single',
    prompt: t('Was übernehmen Access Points im Peppol-Vier-Corner-Modell?', 'What do Access Points handle in the Peppol four-corner model?'),
    options: [
      opt('a', 'Die eigentliche Übermittlung zwischen den Endpunkten', 'The actual transmission between the endpoints'),
      opt('b', 'Die Buchung in der Finanzbuchhaltung', 'Posting to the general ledger'),
      opt('c', 'Die Validierung der Umsatzsteuererklärung', 'Validating the VAT return'),
      opt('d', 'Die Vergabe der Leitweg-ID', 'Issuing the Leitweg-ID'),
    ],
    correctOptionId: 'a',
    explanation: t('Sender und Empfaenger sind je an einen Access Point angebunden, der die Uebermittlung erledigt.', 'Sender and receiver are each connected to an Access Point that handles the transmission.'),
  },
  {
    ...base,
    id: 'ei-a-014',
    type: 'single',
    prompt: t('Wozu dient das Peppol-Teilnehmerverzeichnis?', 'What is the Peppol participant directory for?'),
    options: [
      opt('a', 'Es macht Empfänger über ihre Peppol-ID auffindbar', 'It makes recipients findable via their Peppol ID'),
      opt('b', 'Es speichert Rechnungsinhalte dauerhaft', 'It permanently stores invoice content'),
      opt('c', 'Es ersetzt die Leitweg-ID', 'It replaces the Leitweg-ID'),
      opt('d', 'Es prüft die Umsatzsteuer', 'It checks VAT'),
    ],
    correctOptionId: 'a',
    explanation: t('Ueber das Verzeichnis findet der sendende Access Point den passenden Empfangs-Access-Point.', 'The directory lets the sending Access Point find the matching receiving Access Point.'),
  },
  {
    ...base,
    id: 'ei-a-015',
    type: 'single',
    prompt: t('Was ist bei ZUGFeRD/Factur-X das aufbewahrungspflichtige Original?', 'What is the retention-worthy original for ZUGFeRD/Factur-X?'),
    options: [
      opt('a', 'Die im PDF eingebettete XML', 'The XML embedded in the PDF'),
      opt('b', 'Nur das sichtbare PDF-Layout', 'Only the visible PDF layout'),
      opt('c', 'Ein Ausdruck auf Papier', 'A printout on paper'),
      opt('d', 'Ein Screenshot der Rechnung', 'A screenshot of the invoice'),
    ],
    correctOptionId: 'a',
    explanation: t('Aufbewahrungspflichtig ist der strukturierte Datensatz, nicht die menschenlesbare Ansicht.', 'The structured data set must be retained, not the human-readable view.'),
  },

  // ---------- Multiple Select (5) ----------
  {
    ...base,
    id: 'ei-a-016',
    type: 'multi',
    prompt: t('Welche Aussagen zum EN-16931-Datenmodell sind richtig?', 'Which statements about the EN 16931 data model are correct?'),
    options: [
      opt('a', 'Es ist syntax-unabhängig', 'It is syntax-independent'),
      opt('b', 'Es definiert Gruppen wie Rechnungssteller und Rechnungszeilen', 'It defines groups such as seller and invoice lines'),
      opt('c', 'Nationale Ausprägungen bilden dieselben Gruppen ab', 'National specialisations map the same groups'),
      opt('d', 'Es schreibt eine bestimmte Dateiendung vor', 'It prescribes a specific file extension'),
      opt('e', 'Es ersetzt die Umsatzsteuererklärung', 'It replaces the VAT return'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Das Modell ist bewusst syntax- und formatunabhängig gehalten.', 'The model is deliberately kept independent of syntax and format.'),
  },
  {
    ...base,
    id: 'ei-a-017',
    type: 'multi',
    prompt: t('Welche Aussagen zu CIUS und Extension sind richtig?', 'Which statements about CIUS and extensions are correct?'),
    options: [
      opt('a', 'Eine CIUS macht optionale Felder verpflichtend', 'A CIUS makes optional fields mandatory'),
      opt('b', 'Eine Extension ergänzt zusätzliche Felder', 'An extension adds extra fields'),
      opt('c', 'XRechnung ist eine CIUS', 'XRechnung is a CIUS'),
      opt('d', 'Eine CIUS macht eine Rechnung fuer allgemeine EN-16931-Validatoren ungültig', 'A CIUS makes an invoice invalid for general EN 16931 validators'),
      opt('e', 'Extensions widersprechen der Basisnorm', 'Extensions contradict the base standard'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Beide Mechanismen bleiben zur Basisnorm kompatibel.', 'Both mechanisms stay compatible with the base standard.'),
  },
  {
    ...base,
    id: 'ei-a-018',
    type: 'multi',
    prompt: t('Welche Aussagen zur Validierung sind richtig?', 'Which statements about validation are correct?'),
    options: [
      opt('a', 'Schema-Validierung prüft die Wohlgeformtheit', 'Schema validation checks well-formedness'),
      opt('b', 'Schematron-Regeln prüfen Geschäftsregeln', 'Schematron rules check business rules'),
      opt('c', 'Formale Gültigkeit heißt nicht automatisch inhaltlich richtig', 'Formal validity does not automatically mean the content is correct'),
      opt('d', 'Validierung ersetzt die sachliche Prüfung', 'Validation replaces the factual check'),
      opt('e', 'Eine formal gültige Rechnung kann nicht mehr storniert werden', 'A formally valid invoice can no longer be cancelled'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Formale Prüfung und inhaltliche Prüfung sind zwei getrennte Schritte.', 'Formal validation and content review are two separate steps.'),
  },
  {
    ...base,
    id: 'ei-a-019',
    type: 'multi',
    prompt: t('Welche Aussagen zu Peppol sind richtig?', 'Which statements about Peppol are correct?'),
    options: [
      opt('a', 'Access Points übernehmen die Übermittlung', 'Access Points handle the transmission'),
      opt('b', 'Das Teilnehmerverzeichnis macht Empfänger auffindbar', 'The participant directory makes recipients findable'),
      opt('c', 'Es braucht keine Vorabvereinbarung zwischen den Endpunkten', 'No prior agreement between the endpoints is needed'),
      opt('d', 'Beide Seiten müssen beim selben Access Point registriert sein', 'Both sides must be registered with the same Access Point'),
      opt('e', 'Peppol ersetzt die Leitweg-ID im öffentlichen Sektor', 'Peppol replaces the Leitweg-ID in the public sector'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Sender und Empfaenger duerfen bei unterschiedlichen Access Points angebunden sein, und die Leitweg-ID bleibt ein eigenes Konzept.', 'Sender and receiver may be connected to different Access Points, and the Leitweg-ID remains a separate concept.'),
  },
  {
    ...base,
    id: 'ei-a-020',
    type: 'multi',
    prompt: t('Welche Aussagen zur Archivierung sind richtig?', 'Which statements about archiving are correct?'),
    options: [
      opt('a', 'Aufbewahrungspflichtig ist die strukturierte XML', 'The structured XML must be retained'),
      opt('b', 'Das Original muss über die Frist maschinenlesbar bleiben', 'The original must remain machine-readable for the retention period'),
      opt('c', 'Ein Ausdruck ersetzt das Original nicht', 'A printout does not replace the original'),
      opt('d', 'Ein Screenshot der Rechnung reicht als Original', 'A screenshot of the invoice is sufficient as the original'),
      opt('e', 'Nur das PDF-Layout muss aufbewahrt werden', 'Only the PDF layout needs to be retained'),
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: t('Screenshot und reines Layout ersetzen den strukturierten Datensatz nicht.', 'A screenshot and the plain layout do not replace the structured data set.'),
  },

  // ---------- Slider (3) ----------
  {
    ...base,
    id: 'ei-a-021',
    type: 'slider',
    prompt: t('Wie viele Syntaxen erlaubt EN 16931?', 'How many syntaxes does EN 16931 permit?'),
    min: 0,
    max: 6,
    step: 1,
    unit: t('', ''),
    target: 2,
    tolerance: 0,
    zeroAt: 2,
    explanation: t('UBL und UN/CEFACT CII, genau zwei.', 'UBL and UN/CEFACT CII, exactly two.'),
  },
  {
    ...base,
    id: 'ei-a-022',
    type: 'slider',
    prompt: t('Wie viele Ecken hat das Peppol-Vier-Corner-Modell?', 'How many corners does the Peppol four-corner model have?'),
    min: 0,
    max: 8,
    step: 1,
    unit: t('', ''),
    target: 4,
    tolerance: 0,
    zeroAt: 2,
    explanation: t('Sender, Empfänger und deren jeweilige Access Points, zusammen vier.', 'Sender, receiver and their respective Access Points, four in total.'),
  },
  {
    ...base,
    id: 'ei-a-023',
    type: 'slider',
    prompt: t(
      'Wie viele Profilstufen zeigt die ZUGFeRD-Profiltreppe in diesem Kurs (von minimal bis erweitert)?',
      'How many profile levels does the ZUGFeRD profile ladder in this course show (from minimal to extended)?',
    ),
    min: 0,
    max: 8,
    step: 1,
    unit: t('', ''),
    target: 4,
    tolerance: 0,
    zeroAt: 2,
    explanation: t('Die Grafik zeigt vier Stufen mit steigendem Detailgrad.', 'The figure shows four levels with increasing detail.'),
  },

  // ---------- Zuordnung (2) ----------
  {
    ...base,
    id: 'ei-a-024',
    type: 'matching',
    prompt: t('Ordne jeden Begriff seiner Bedeutung zu.', 'Match each term to its meaning.'),
    left: [
      opt('cius', 'CIUS', 'CIUS'),
      opt('extension', 'Extension', 'Extension'),
      opt('schema', 'Schema-Validierung', 'Schema validation'),
      opt('schematron', 'Schematron', 'Schematron'),
      opt('leitweg', 'Leitweg-ID', 'Leitweg-ID'),
    ],
    right: [
      opt('einschraenkung', 'Einschränkung der Norm mit Pflichtfeldern', 'Restriction of the standard with mandatory fields'),
      opt('ergaenzung', 'Ergänzung um zusätzliche, branchenspezifische Felder', 'Addition of extra, sector-specific fields'),
      opt('wohlgeformt', 'Prüft, ob das XML wohlgeformt ist', 'Checks whether the XML is well-formed'),
      opt('geschaeftsregeln', 'Prüft semantische Geschäftsregeln', 'Checks semantic business rules'),
      opt('verwaltung', 'Identifiziert die zuständige Verwaltungsstelle', 'Identifies the responsible administrative body'),
    ],
    pairs: { cius: 'einschraenkung', extension: 'ergaenzung', schema: 'wohlgeformt', schematron: 'geschaeftsregeln', leitweg: 'verwaltung' },
    explanation: t('Fuenf zentrale Begriffe der vertieften E-Rechnung.', 'Five key terms of e-invoicing in depth.'),
  },
  {
    ...base,
    id: 'ei-a-025',
    type: 'matching',
    prompt: t('Ordne jeden Begriff seiner Rolle im Peppol-Netzwerk zu.', 'Match each term to its role in the Peppol network.'),
    left: [
      opt('accesspoint', 'Access Point', 'Access Point'),
      opt('verzeichnis', 'Teilnehmerverzeichnis', 'Participant directory'),
      opt('vierecorner', 'Vier-Corner-Modell', 'Four-corner model'),
      opt('peppolid', 'Peppol-ID', 'Peppol ID'),
      opt('bis', 'Peppol BIS Billing', 'Peppol BIS Billing'),
    ],
    right: [
      opt('uebermittlung', 'Übernimmt die Übermittlung zwischen den Endpunkten', 'Handles the transmission between the endpoints'),
      opt('auffindbar', 'Macht Teilnehmer auffindbar', 'Makes participants findable'),
      opt('vierrollen', 'Beschreibt die vier beteiligten Rollen', 'Describes the four roles involved'),
      opt('kennung', 'Eindeutige Kennung eines Teilnehmers', 'Unique identifier of a participant'),
      opt('format', 'Das dort verwendete Rechnungsformat', 'The invoice format used there'),
    ],
    pairs: { accesspoint: 'uebermittlung', verzeichnis: 'auffindbar', vierecorner: 'vierrollen', peppolid: 'kennung', bis: 'format' },
    explanation: t('Transportweg, Verzeichnis und Format sind unterschiedliche Ebenen von Peppol.', 'Transport, directory and format are different layers of Peppol.'),
  },
]
